server:
    port: 8888

spring:
    application:
        name: config-server
    cloud:
        config:
            enabled: true
            server:
                git:
                    uri: https://github.com/nestorhasin/config-client-kafka.git
                default-label: master

management:
    endpoints:
        web:
            exposure:
                include: '*'